[package]
name = "lnav-rs-ext"
publish = false
version = "0.11.3"

edition = "2021"
rust-version = "1.70.0"

# This means we can build with `--features=default`, which can make builds more generic
[features]
default = []

[lib]
# We produce both of these at the moment, but could consider refining this. ref
# https://github.com/rust-lang/cargo/issues/8607 &
# https://github.com/rust-lang/rust/issues/59302
crate-type = ["staticlib"]
doctest = false
test = false
doc = false

[dependencies]
# Build latest: 
# prqlc = { git = "https://github.com/PRQL/prql.git" }
# Build deterministic:
prqlc = "0.13.6"
cxx = "1.0"
log = "0.4"
miette = "7.6.0"
log2src = {git = "https://github.com/tstack/log2src.git", branch = "caching1"}
# log2src = {path = "/Users/tstack/github/log2src"}
rouille = "3.6.2"
cookie = "0.18.1"
serde_json = "1.0.143"
serde = { version = "1.0.219", features = ["derive"] }
uuid = { version = "1.18.1", features = ["v4"]}

[build-dependencies]
cxx-build = "1.0"

[package.metadata.release]
tag-name = "{{version}}"
tag-prefix = ""
